[build]
command = "npm ci && npm run build"
publish = "build/client"

[build.environment]
NODE_VERSION = "20"
NPM_FLAGS = "--no-optional --legacy-peer-deps"

[dev]
command = "npm run dev"
framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames
[[headers]]
for = "/build/*"

[headers.values]
"Cache-Control" = "public, max-age=31560000, immutable"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200